name: Shell-Scripting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: change mode
      run:  cd LINUX_PROJECT && chmod a+x release.sh
    - name: shell testing
      run:  cd LINUX_PROJECT && ./release.sh
    
